name: Update Blog

on:
  workflow_dispatch:
  repository_dispatch: 
    types: [update-submodule-trigger]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodule
        run: |
          cd src/lib/blog
          git fetch origin
          git checkout main
          git pull origin main
          cd ../..


      - name: Commit submodule update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/lib/blog

          # Things we can ignore from the blog repository
          IGNORE_LIST=(
            "src/lib/blog/.github/workflows"
            "src/lib/blog/README.md"
            "src/lib/blog/LICENSE"
          )

          # Unstage ignored paths
          for path in "${IGNORE_LIST[@]}"; do
            git reset "$path"
          done

          if git diff-index --quiet HEAD; then
            echo "No changes in submodule blog"
          else
            git commit -m "Update submodule blog"
            git push origin HEAD
          fi
